// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkK_iTsD2yhCpz8aB_ro8g8wGcRGwCQ9g',
    appId: '1:661919374817:web:93a75a766f61db88a846a0',
    messagingSenderId: '661919374817',
    projectId: 'shopping-hero-94c87',
    authDomain: 'shopping-hero-94c87.firebaseapp.com',
    storageBucket: 'shopping-hero-94c87.firebasestorage.app',
    measurementId: 'G-MR781T6LV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHA7nqA3ynNpCfvFwNBFG6xfVPPGsT-CQ',
    appId: '1:661919374817:android:3d4166775e3a0dbba846a0',
    messagingSenderId: '661919374817',
    projectId: 'shopping-hero-94c87',
    storageBucket: 'shopping-hero-94c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbhR0yAAr7DvGx3jGCjle1woDXF1mZ9aI',
    appId: '1:661919374817:ios:337572f54feec324a846a0',
    messagingSenderId: '661919374817',
    projectId: 'shopping-hero-94c87',
    storageBucket: 'shopping-hero-94c87.firebasestorage.app',
    iosBundleId: 'com.example.shoppingHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbhR0yAAr7DvGx3jGCjle1woDXF1mZ9aI',
    appId: '1:661919374817:ios:337572f54feec324a846a0',
    messagingSenderId: '661919374817',
    projectId: 'shopping-hero-94c87',
    storageBucket: 'shopping-hero-94c87.firebasestorage.app',
    iosBundleId: 'com.example.shoppingHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkK_iTsD2yhCpz8aB_ro8g8wGcRGwCQ9g',
    appId: '1:661919374817:web:e744a8d305fac770a846a0',
    messagingSenderId: '661919374817',
    projectId: 'shopping-hero-94c87',
    authDomain: 'shopping-hero-94c87.firebaseapp.com',
    storageBucket: 'shopping-hero-94c87.firebasestorage.app',
    measurementId: 'G-Q0PRN7Z9WY',
  );
}
